spring:
  rabbitmq:
    addresses: mq-1.rabbitmq.idc.cedu.cn:5672,mq-2.rabbitmq.idc.cedu.cn:5672,mq-3.rabbitmq.idc.cedu.cn:5672
    virtual-host: socialiosvc
    username: socialiosvc
    password: socialiosvc